use Mix.Config

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.
#
# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :photography, PhotographyWeb.Endpoint,
  http: [port: System.get_env("PORT") || 4000],
  url: [host: "1aus2.de/photos/", port: 443],
  cache_static_manifest: "priv/static/cache_manifest.json",
  server: true,
  code_reloader: false,
  root: ".",
  version: Application.spec(:phoenix_distillery, :vsn),
  live_reload: [
    patterns: [
      ~r{lib/saison_kalender_phx_web/live/.*(ex)$}
    ]
  ]


# Do not print debug messages in production
config :logger, level: :info

config :phoenix, :serve_endpoints, true
import_config "prod.secret.exs"
